name: flutter_test_sample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  cached_network_image: ^3.2.3
  get_it: ^7.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.0
  mockito: ^5.3.2
  bloc_test: ^9.1.0

dependency_overrides:
  analyzer: '>=1.0.0 <3.0.0'

flutter:

  uses-material-design: true